name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger on pushes to the `main` branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"  # Use the desired Python version

    # Step 3: Install dependencies
    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Set BASE_URL
      id: set_base_url
      run: |
        REPO_NAME=$(basename $GITHUB_REPOSITORY)
        BASE_URL="https://$GITHUB_ACTOR.github.io/$REPO_NAME"
        echo "BASE_URL=$BASE_URL" >> $GITHUB_ENV

    # Step 4: Run the script to generate static files
    - name: Generate static files
      working-directory: src
      run: python main.py

    # Step 5: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output  # Path to the output folder
